application:
  env: prd

database:
  dev:
    name: BDTCCHOM
    username: postgres
    password: 123456
    host: localhost
    port: 5432
  prd:
    name: BDTCCPROD
    username: postgres
    password: 123456
    host: localhost
    port: 5432